version: '3'
services:
  web:
    container_name: "ytdownload"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8501
    expose:
      - 8501